services:

  api:
    build: .
    container_name: tenanthub_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: tenanthub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenanthub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: tenanthub_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "${POSTGRES_EXPORTER_DSN}"

    ports:
      - "9187:9187"
    depends_on:
      - postgres

  redis:
    image: redis:8
    container_name: tenanthub_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: tenanthub_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: tenanthub_redis_exporter
    environment:
      REDIS_ADDR: redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: tenanthub_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: tenanthub_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: tenanthub_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml




  alloy:
    image: grafana/alloy:latest
    container_name: tenanthub_alloy
    ports:
      - "12345:12345"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
    command:
      - run
      - /etc/alloy/config.alloy

volumes:
  postgres_data:
  grafana_data:
