apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: syedshoib-dev

type: Opaque

stringData:
  DATABASE_URL: "postgresql+asyncpg://neondb_owner:npg_FQNbamJ16oMB@ep-mute-wave-axzngr63-pooler.c-4.us-east-2.aws.neon.tech/neondb?ssl=require"
  JWT_SECRET: "YOUR_LONG_RANDOM_JWT_SECRET"
