apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: tenanthub

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: tenanthub-api:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          envFrom:
            - configMapRef:
                name: api-config

            - secretRef:
                name: api-secret

---
apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: tenanthub

spec:
  selector:
    app: api

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP
